version: '3.7'

networks:
  pricelist:
    driver_opts:
      com.docker.network.bridge.name: pricelist
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.1/16
services:
  cloud:
    image: cloud
    working_dir: /usr/cloud
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      pricelist:
        ipv4_address: ${APP_HOST}

  db:
    image: mysql
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}
    networks:
      pricelist:
        ipv4_address: ${MYSQL_HOST}
