version: '3.7'

networks:
  pricelist:
    driver_opts:
      com.docker.network.bridge.name: pricelist
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.1/16
services:
  cloud:
    image: cloud
    working_dir: /usr/cloud
    ports:
      - "8080:8080"
    networks:
      pricelist:
        ipv4_address: 172.16.0.2